### ISSUE TITLE
Stack

### ISSUE THREAD

**Issue by joaosvc** [JkqzDev/ItemStacker#1]
it is not necessary to check the entity type inside the loop, just pass its class in getNearbyEntities

Exemple: 
getNearbyEntities($boudingBox, ItemEntity::class)

**Comment by JkqzDev** [comment]
> it is not necessary to check the entity type inside the loop, just pass its class in getNearbyEntities
> 
> Exemple: getNearbyEntities($boudingBox, ItemEntity::class)

The second argument to the `getNearbyEntities` function is to ignore an entity.

https://github.com/pmmp/PocketMine-MP/blob/674b65f789c193cb221027c7f71a37d83074d877/src/world/World.php#L2205
