### ISSUE TITLE
Entitiy validation (dup)

### ISSUE THREAD

**Issue by joaosvc** [JkqzDev/ItemStacker#2]
during reading, it can cause a dup, so put a check if the entity is already being removed

Exemple:

if ($entity->isFlaggedForDespawn()) {
        continue;
}

**Comment by JkqzDev** [comment]
> during reading, it can cause a dup, so put a check if the entity is already being removed
> 
> Exemple:
> 
> if ($entity->isFlaggedForDespawn()) { continue; }

Fixed :)

Thanks for your report
